---
title: "creating correlation table"
output: html_notebook
---

# APA style table for GT package
https://gist.github.com/pdparker/1b61b6d36d09cb295bf286a931990159
```
# Provides APA 7th Styling to a table ####
# Only works using the global-font-options branch of the gt package
#Requires
library(gt)
library(tidyverse)

# APA style ####
apa_style <- function(data) {
  data %>%
    opt_table_lines(extent = "none") %>%
    tab_options(
      heading.border.bottom.width = 2,
      heading.border.bottom.color = "black",
      heading.border.bottom.style = "solid",
      table.border.top.color = "white",
      table_body.hlines.color = "white",
      table_body.border.top.color = "black",
      table_body.border.top.style = "solid",
      table_body.border.top.width = 1,
      heading.title.font.size = 12,
      table.font.size = 12,
      heading.subtitle.font.size = 12,
      table_body.border.bottom.color = "black",
      table_body.border.bottom.width = 1,
      table_body.border.bottom.style = "solid",
      column_labels.border.bottom.color = "black",
      column_labels.border.bottom.style = "solid",
      column_labels.border.bottom.width = 1
    ) %>%
      opt_table_font(font = "times")
}
```

# 상관관계 표 만들기
아래 두 방법이 결합하는게 더 간단 
https://www.datadreaming.org/post/apa-tables-using-rmarkdown-part-3/
https://stefaneng.github.io/apa_correlation_table/

```
apply_if <- function(mat, p, f) {
  # Fill NA with FALSE
  p[is.na(p)] <- FALSE
  mat[p] <- f(mat[p])
  mat
}
apaCorr <- function(mat, corrtype = "pearson") {
  matCorr <- mat
  if (class(matCorr) != "rcorr") {
    matCorr <- rcorr(mat, type = corrtype)
  }

  # Add one star for each p < 0.05, 0.01, 0.001
  stars <- apply_if(round(matCorr$r, 2), matCorr$P < 0.05, function(x) paste0(x, "*"))
  stars <- apply_if(stars, matCorr$P < 0.01, function(x) paste0(x, "*"))
  stars <- apply_if(stars, matCorr$P < 0.001, function(x) paste0(x, "*"))
  # Put - on diagonal and blank on upper diagonal
  stars[upper.tri(stars, diag = T)] <- "-"
  stars[upper.tri(stars, diag = F)] <- ""
  n <- length(stars[1,])
  colnames(stars) <- 1:n
  # Remove _ and convert to title case
  row.names(stars) <- tools::toTitleCase(sapply(row.names(stars), gsub, pattern="_", replacement = " "))
  # Add index number to row names
  row.names(stars) <- paste(paste0(1:n,"."), row.names(stars))
  stars
}

options(digits = 3)
v5889_df %>% dplyr::select(대면빈도, 비대면빈도, 대면인원, 비대면인원, 우울불안, 삶만족) -> df

df %>% map_dfc(mean) %>% fashion(decimals = 2) %>% as_tibble() %>% 
  pivot_longer(everything(), names_to = "Mname", values_to = "M") -> mean_df
df %>% map_dfc(sd) %>% fashion(decimals = 2) %>% as_tibble() %>% 
  pivot_longer(everything(), names_to = "SDname", values_to = "SD") -> sd_df
df %>% correlate() %>% shave(upper = T) %>% 
  fashion(decimals = 2, na_print = "-") %>% as_tibble() -> cor_df
df %>% as.matrix() %>% apaCorr(corrtype = "pearson") %>% 
  as.data.frame() -> cor_df
tibble(Variable = c(
  "1. F2F Frequency ",
  "2. CMC Frequency",
  "3. F2F Network Size",
  "4. CMC Network Size",
  "5. Ill-being",
  "6. Well-being"
)) -> row_df

bind_cols(row_df, mean_df[2], sd_df[2], cor_df) %>% 
  gt() %>% gt_theme_538() %>% 
  tab_header(md("**Table 1** Descriptive Statistics and Correlations for Study Variables")
  ) %>% cols_label(
    M = md("*M*"), SD = md("*SD*")
  ) %>% cols_width(
    Variable ~ px(180)
  ) %>% tab_source_note(
    source_note = md("_Note._ * _p_ < .05,  ** _p_ < .01,  *** _p_ < .001  
                     F2F = Face-to-Face, CMC = Computer Mediated Communication")
  )

```

이전 방식. 다소 복잡. 

### required packages

```{r}
if(!require(Hmisc)) install.packages("Hmisc")
if(!require(dplyr)) install.packages("dplyr")
```

```{r}
names(iris)
df <- iris
var <- 1:4
dcor.df <- df[var]
names(dcor.df)
```



### 오른쪽 위 값 지우기 
```{r}
cor.r <- cor(dcor.df)
cor2.r<- round(cor.r, 2)

upper <- cor2.r 
upper[upper.tri(upper)] <- ""
upper
class(upper)
upper <- apply(upper, 2, as.numeric)

colnames(upper) <- 1:length(upper[1,])

upper

```
corrr패키지의 shave()함수도 같은 기능. 
https://www.tidyverse.org/blog/2020/12/corrr-0-4-3/


### 평균과 표준편자 행 추가하고, 열 이름 만들기 
```{r}
upper.df <- as.data.frame(upper)
dmean.df <- apply(dcor.df,2, mean)
dmean.df <- round(dmean.df, 2)
dsd.df <- apply(dcor.df,2, sd)
dsd.df <- round(dsd.df, 2)

upper.df <- rbind(upper.df, dmean.df)
upper.df <- rbind(upper.df, dsd.df)
rownames(upper.df) <- c(
  "꽃받침 길이", 
  "꽃받침 넓이", 
  "꽃잎 길이", 
  "꽃잎 넓이",
  "평균", 
  "표준편차" )

upper.df
coef.df <- upper.df
```



### P값 데이터프레임 만들기
```{r}
library(dplyr)
dcor.r <- dcor.df %>% as.matrix %>% Hmisc::rcorr(.)
options(digits = 3)
dcor.r$P
sig.m <- as.matrix(dcor.r$P)

# hide upper
upper <- sig.m
upper[upper.tri(upper)] <- ""
sig.m <- upper

sig.df <- as.data.frame(sig.m, stringsAsFactors = F)
sig.df <- as.data.frame(apply(sig.df, 2, as.numeric))

s.df <- round(sig.df, 3)

for(i in 1:ncol(s.df)){
  s.df[which(s.df[,i] <= .001), i] <- "***"
  s.df[which(s.df[,i] <= .01 & s.df[,i] > .001), i] <- "**"
  s.df[which(s.df[,i] <= .05 & s.df[,i] > .01), i] <- "*"  
  s.df[which(s.df[,i] <= 1 & s.df[,i] > .05), i] <- NA
  
}; s.df

sig.df <- s.df
colnames(sig.df) <- paste0("p", 1:ncol(sig.df))
sig.df
```



### 상관계수와 P값 데이터프레임 합하기 
```{r}
empty.df <- matrix( rep(NA, ncol(sig.df)*2), 
       nrow = 2, ncol = ncol(sig.df) , byrow = T ) %>% as.data.frame()
colnames(empty.df) <- paste0("p", 1:ncol(sig.df))
sig.df <- rbind(sig.df, empty.df)
cor2.df <- cbind(coef.df, sig.df )
names(cor2.df)

# convert dataframe to vector
df <- data.frame(v1 = 1:ncol(sig.df), v2 = 1:ncol(sig.df)+ncol(sig.df))
var <- c()
for(i in 1:ncol(sig.df)){
  var <- c(var, as.numeric(df[i,]) )
}
var

names(cor2.df[var])

cor2.df <- cor2.df[var]
cor2.df
write.csv(cor2.df, "table_cor.csv")

```

